[phases.setup]
aptPkgs = [
  "chromium-browser",
  "chromium-browser-l10n",
  "libgbm1",
  "libnss3",
  "libatk-bridge2.0-0",
  "libdrm2",
  "libxkbcommon0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2"
]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
NPM_CONFIG_PRODUCTION = "false"
